version: "3"

services:
  web:
    image: nginx:alpine
    volumes:
      - ./frontend/:/usr/share/nginx/html:ro
      - ./config/nginx.conf:/etc/nginx/conf.d/default.conf:ro
    restart: "always"
    ports:
      - "10029:80"
    networks:
      - default
  db:
    image: mariadb:latest
    environment:
      MYSQL_DATABASE: store
      MYSQL_ROOT_PASSWORD: 123456
    volumes:
      - ./config/db.sql:/docker-entrypoint-initdb.d/db.sql
    restart: "always"
    networks:
      - default
  backend:
    build: ./backend/
    restart: "always"
    depends_on:
      - db
    networks:
      - default